apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-mysql
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ include "wordpress-stack.fullname" . }}-mysql

          {{- if .Values.mysql.persistence.enabled }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
          {{- end }}

      {{- if .Values.mysql.persistence.enabled }}
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.persistence.existingClaim | default (printf "%s-mysql-pvc" (include "YOURCHART.fullname" .)) }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-mysql
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
