apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-mysql
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
