apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-wordpress
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ default 3 .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: wordpress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ default "wordpress" .Values.wordpress.image.repository }}:{{ default "latest" .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.wordpress.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ printf "%s-mysql" (include "wordpress-stack.fullname" .) | quote }}

            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-stack.fullname" . }}-mysql
                  key: MYSQL_USER

            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-stack.fullname" . }}-mysql
                  key: MYSQL_PASSWORD

            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wordpress-stack.fullname" . }}-mysql
                  key: MYSQL_DATABASE

          {{- if .Values.wordpress.configExtra }}
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
{{ .Values.wordpress.configExtra | indent 16 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-stack.fullname" . }}-wordpress
  labels:
    {{- include "wordpress-stack.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.wordpress.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "wordpress-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wordpress
  ports:
    - name: http
      protocol: TCP
      port: {{ default 80 .Values.wordpress.service.port }}
      targetPort: http
