{{- if .Values.apps.enabled }}
{{- if .Values.apps.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webmvc-ingress
  namespace: {{ include "tp.ns" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.apps.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.apps.ingress.host }}
      secretName: {{ .Values.apps.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.apps.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.apps.webmvc.name }}
                port:
                  number: 80
{{- end }}
{{- end }}
